[build]
  command = "pnpm build"
  publish = "build/client"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["build/server/**"]

[build.environment]
  NODE_VERSION = "20"
  COREPACK_ENABLE_DOWNLOAD_PROMPT = "0"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  force = false
